ALTER TABLE "user" ALTER COLUMN "name" DROP NOT NULL;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "account_refresh_token_expires_at_idx" ON "account" USING btree ("refreshTokenExpiresAt");--> statement-breakpoint
CREATE INDEX "lora_user_id_idx" ON "loras" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "lora_trigger_word_idx" ON "loras" USING btree ("trigger_word");--> statement-breakpoint
CREATE INDEX "lora_created_at_idx" ON "loras" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "media_generation_task_user_id_idx" ON "media_generation_task" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "media_generation_task_user_id_status_idx" ON "media_generation_task" USING btree ("user_id","status");--> statement-breakpoint
CREATE INDEX "media_generation_task_status_idx" ON "media_generation_task" USING btree ("status");--> statement-breakpoint
CREATE INDEX "media_generation_task_is_private_deleted_at_idx" ON "media_generation_task" USING btree ("is_private","deleted_at");--> statement-breakpoint
CREATE INDEX "media_generation_task_is_nsfw_deleted_at_idx" ON "media_generation_task" USING btree ("is_nsfw","deleted_at");--> statement-breakpoint
CREATE INDEX "media_generation_task_deleted_at_idx" ON "media_generation_task" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX "media_generation_task_created_at_idx" ON "media_generation_task" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "media_generation_task_task_type_idx" ON "media_generation_task" USING btree ("task_type");--> statement-breakpoint
CREATE INDEX "media_generation_task_provider_request_id_idx" ON "media_generation_task" USING btree ("provider_request_id");--> statement-breakpoint
CREATE INDEX "quota_user_id_idx" ON "quota" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "quota_user_id_expires_at_idx" ON "quota" USING btree ("user_id","expires_at");--> statement-breakpoint
CREATE INDEX "quota_type_idx" ON "quota" USING btree ("type");--> statement-breakpoint
CREATE INDEX "quota_transaction_user_id_idx" ON "quota_transaction" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "quota_transaction_user_id_created_at_idx" ON "quota_transaction" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "quota_transaction_type_idx" ON "quota_transaction" USING btree ("type");--> statement-breakpoint
CREATE INDEX "quota_transaction_related_transaction_id_idx" ON "quota_transaction" USING btree ("related_transaction_id");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "session_expires_at_idx" ON "session" USING btree ("expiresAt");--> statement-breakpoint
CREATE INDEX "subscription_user_id_idx" ON "subscription" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "subscription_user_id_status_idx" ON "subscription" USING btree ("user_id","status");--> statement-breakpoint
CREATE INDEX "subscription_payment_subscription_id_idx" ON "subscription" USING btree ("payment_subscription_id");--> statement-breakpoint
CREATE INDEX "subscription_next_billing_at_idx" ON "subscription" USING btree ("next_billing_at");--> statement-breakpoint
CREATE INDEX "subscription_status_idx" ON "subscription" USING btree ("status");--> statement-breakpoint
CREATE INDEX "transaction_user_id_idx" ON "transaction" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "transaction_user_id_created_at_idx" ON "transaction" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "transaction_payment_transaction_id_idx" ON "transaction" USING btree ("payment_transaction_id");--> statement-breakpoint
CREATE INDEX "transaction_type_idx" ON "transaction" USING btree ("type");--> statement-breakpoint
CREATE INDEX "user_is_admin_idx" ON "user" USING btree ("is_admin");--> statement-breakpoint
CREATE INDEX "user_type_idx" ON "user" USING btree ("user_type");--> statement-breakpoint
CREATE INDEX "user_registration_country_idx" ON "user" USING btree ("registration_country");--> statement-breakpoint
CREATE INDEX "user_created_at_idx" ON "user" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "verification" USING btree ("identifier");--> statement-breakpoint
CREATE INDEX "verification_expires_at_idx" ON "verification" USING btree ("expiresAt");