import { TaskData } from '../types';
import { siteConfig } from '@/config/site';

/**
 * 生成 Schema.org 结构化数据
 */
export function generateStructuredData(task: TaskData, prompt: string, model: string, siteUrl: string) {
  return {
    '@context': 'https://schema.org',
    '@type': 'ImageGallery',
    name: prompt,
    description: `AI generated images using ${model}`,
    author: {
      '@type': 'Organization',
      name: siteConfig.name,
      url: siteUrl,
      logo: `${siteUrl}/logo.png`,
    },
    dateCreated: task.created_at,
    copyrightNotice: `© ${new Date().getFullYear()} ${siteConfig.name}. All rights reserved.`,
    creator: {
      '@type': 'Organization',
      name: siteConfig.name,
      url: siteUrl,
    },
    creditText: `Generated by ${siteConfig.name} using ${model}`,
    image: task.results?.map((result) => ({
      '@type': 'ImageObject',
      contentUrl: result.url,
      description: prompt,
      datePublished: task.created_at,
      creator: {
        '@type': 'SoftwareApplication',
        name: model,
      },
      copyrightNotice: `© ${new Date().getFullYear()} ${siteConfig.name}. All rights reserved.`,
      creditText: `Generated by ${siteConfig.name} using ${model}`,
    })) || [],
  };
}
