/**
 * 订阅计划配置
 */

import { SUBSCRIPTION_PLANS, type SubscriptionPlanType } from './pricing';

// 重新导出订阅计划常量，方便其他模块使用
export { SUBSCRIPTION_PLANS, type SubscriptionPlanType };

/**
 * 年付订阅积分系数
 */
const ANNUAL_SUBSCRIPTION_POINTS_COEFFICIENT = 1.2;

/**
 * 订阅计划积分系数
 */
const SUBSCRIPTION_PLAN_POINTS_COEFFICIENT = {
  [SUBSCRIPTION_PLANS.MONTHLY_HOBBY]: 1.2, // 爱好版月付积分系数
  [SUBSCRIPTION_PLANS.YEARLY_HOBBY]: 1.2 * ANNUAL_SUBSCRIPTION_POINTS_COEFFICIENT, // 爱好版年付积分系数
  [SUBSCRIPTION_PLANS.MONTHLY_BASIC]: 1.5, // 基础版月付积分系数
  [SUBSCRIPTION_PLANS.YEARLY_BASIC]: 1.5 * ANNUAL_SUBSCRIPTION_POINTS_COEFFICIENT, // 基础版年付积分系数
  [SUBSCRIPTION_PLANS.MONTHLY_PRO]: 2, // 专业版月付积分系数
  [SUBSCRIPTION_PLANS.YEARLY_PRO]: 2 * ANNUAL_SUBSCRIPTION_POINTS_COEFFICIENT, // 专业版年付积分系数
} as const;

// 订阅计划配额配置
export const SUBSCRIPTION_QUOTA_CONFIG: Record<string, number> = {
  // 爱好版 - 月付
  [SUBSCRIPTION_PLANS.MONTHLY_HOBBY]: 1000 * SUBSCRIPTION_PLAN_POINTS_COEFFICIENT[SUBSCRIPTION_PLANS.MONTHLY_HOBBY],

  // 爱好版 - 年付
  [SUBSCRIPTION_PLANS.YEARLY_HOBBY]: 1000 * 12 * SUBSCRIPTION_PLAN_POINTS_COEFFICIENT[SUBSCRIPTION_PLANS.YEARLY_HOBBY],

  // 基础版 - 月付
  [SUBSCRIPTION_PLANS.MONTHLY_BASIC]: 3000 * SUBSCRIPTION_PLAN_POINTS_COEFFICIENT[SUBSCRIPTION_PLANS.MONTHLY_BASIC],

  // 基础版 - 年付
  [SUBSCRIPTION_PLANS.YEARLY_BASIC]: 3000 * 12 * SUBSCRIPTION_PLAN_POINTS_COEFFICIENT[SUBSCRIPTION_PLANS.YEARLY_BASIC],

  // 专业版 - 月付
  [SUBSCRIPTION_PLANS.MONTHLY_PRO]: 10000 * SUBSCRIPTION_PLAN_POINTS_COEFFICIENT[SUBSCRIPTION_PLANS.MONTHLY_PRO],

  // 专业版 - 年付
  [SUBSCRIPTION_PLANS.YEARLY_PRO]: 10000 * 12 * SUBSCRIPTION_PLAN_POINTS_COEFFICIENT[SUBSCRIPTION_PLANS.YEARLY_PRO],
};

/**
 * 获取订阅计划对应的积分数量
 */
export function getSubscriptionQuota(planType: string): number {
  return SUBSCRIPTION_QUOTA_CONFIG[planType] || 0;
}

/**
 * 检查是否为有效的订阅计划
 */
export function isValidSubscriptionPlan(planType: string): boolean {
  return planType in SUBSCRIPTION_QUOTA_CONFIG;
}
